### ISSUE TITLE
Persistent progress bar after first wcvp_match_names() use

### ISSUE THREAD

**Issue by pgomba** [matildabrown/rWCVP#49]
Hi, 
the progress bar from `wcvp_match_names()` with `progress_bar=TRUE` works well the first time. But if  `wcvp_match_names()` is used again the progress is spammed everytime the function uses a function from `cli::`. 
I have tested this only in one computer. If I run `wcvp_match_names()` and afterwards I run, for example `cli::cli_h1("test")`, the message "test" appears in the console terminal followed by the last state of the progress bar (see attached file). 
I think the "problem" might be related to the function `edit_match()`, within the function `wcvp_match_fuzzy()`, in particuar this this bit ` withr::local_options(list(cli.progress_show_after = 2, cli.progress_clear = FALSE))`, but I have not been able to solve it. Maybe the progress bar is not reaching 100% and the environment keeps the info?

My main issue is that I use cli:: in other functions and now I have a frozen progress bar showing everywhere! :D

![Captura](https://user-images.githubusercontent.com/95383762/230744767-a57aa958-344a-4e7c-b7f3-7a238e1e6aa8.PNG)

**Comment by matildabrown** [comment]
Interesting - I just tested and it only happens on my machine when I explicitly call `progress_bar=TRUE` (but not when it is left out, even though `TRUE` is the default). Can you confirm that this is the same on your machine? 
Will look into this ASAP.

**Comment by pgomba** [comment]
The issue still exists for me on a clean session with `progress_bar=TRUE` left out. 
I've tested it using a different subsample of my species list (n=400), and the progress bar stops at 98%. 
Happy to have a Teams meeting if makes things easier!

**Comment by matildabrown** [comment]
Fixed in branch, will close when merged
