### ISSUE TITLE
timeout in reaching the kew API

### ISSUE THREAD

**Issue by azizka** [matildabrown/rWCVP#59]
Hi, thanks for the awesome package!

I am getting 

>Error in curl::curl_fetch_memory(url, handle = handle) : 
>  Timeout was reached: [sftp.kew.org] Failed to connect to sftp.kew.org port 80 after 10012 ms: Timeout was reached

with a functioning high speed internet connection, and a script that worked yesterday. Is there a problem with the API?

R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

**Comment by barnabywalker** [comment]
Hi Alex,

Unfortunately it looks like the sftp server holding the WCVP is down. rWCVP makes a request to it to check the version of the WCVP data you’re using unless you have a local copy. 

Matilda’s put a workaround in #58 and we’re working on a more permanent fix now.

**Comment by matildabrown** [comment]
Adding a couple more details for anyone else who is having this issue: `rWCVPdata` contains a copy of the WCVP that can be used as a 'local copy' via the workaround (#58) and as far as I know should still be installable, so will work even if you are using the package for the first time.

**Comment by azizka** [comment]
great, thanks
