### ISSUE TITLE
How update rWCVPdata?

### ISSUE THREAD

**Issue by eortizb** [matildabrown/rWCVP#61]
How can I update rWCVPdata to use it in rWCVP?

**Comment by matildabrown** [comment]
Instructions here: 
https://github.com/matildabrown/rWCVPdata#installation 

It's still at v11, but v12 can be downloaded and used as a local copy from: https://kew.iro.bl.uk/concern/datasets/32f77ea6-0f7b-4b2d-b7b3-173ed4ca2d6a?locale=en

**Comment by eortizb** [comment]
Thanks for the information. I do know the datasets page with WCVP updates. But I don't know when I run the wcvp_match_names function how to indicate that it will work with that updated dataset

**Comment by matildabrown** [comment]
You can point it to a specific (local) version of the WCVP using the `wcvp_names` argument - see documentation at https://matildabrown.github.io/rWCVP/reference/wcvp_match_names.html (note that this method can be used for all functions, but some will also require the `wcvp_distributions` argument if using a local copy of the WCVP).

To read in the .txt file, we recommend using `read.table("wcvp_names.csv", sep="|", header=TRUE, quote = "", fill=TRUE, encoding = "UTF-8")`

**Comment by eortizb** [comment]
This is useful to me. Thank you.

**Comment by matildabrown** [comment]
No worries, glad to hear it! 😊 Feel free to reopen if any issues.
