### ISSUE TITLE
Updating the data files

### ISSUE THREAD

**Issue by cbud** [matildabrown/rWCVP#64]
I noticed that you're data files for WCVP are two years old, and the parsing of the downloaded data from the kew website or GBIF seems to have changed.

**Comment by matildabrown** [comment]
Hi Chris, 
Thanks for the nudge to update the `drat` repo - it should be working with the current version of `rWCVPdata` now. The most up-to-date version (currently version 13 of WCVP, from May 2024), can always be installed using:
```
devtools::install_github("matildabrown/rWCVPdata")
```

We've had a couple challenges getting updates of `rWCVP` onto CRAN so we recommend working with the development version of it, too: 

```
devtools::install_github("matildabrown/rWCVP")
```

Please let me know if you have any further issues with the packages - happy to reopen if necessary.
